### ISSUE TITLE
How can i backup files to my folder.

### ISSUE THREAD

**Issue by yonh** [rastersoft/cronopete#20]
How can i backup files to my folder? not usb disk.

**Comment by rastersoft** [comment]
Cronopete doesn't allow to do that. You must do a backup to another physical drive, because the idea is to be able to recover your files even if your hard disk dies (which is something more common than what you think...). Doing backups in the same drive is a very bad idea, and since cronopete aims to be a tool for common people, not for experts, it forces you to do the things right.

Of course you can use an internal hard disk, but in that case you must check the "Show all drives" option when choosing the destination drive.
