### ISSUE TITLE
Requirement to format disk for backup target seems to be broken

### ISSUE THREAD

**Issue by bnlawrence** [rastersoft/cronopete#24]
My current setup is that I am using cronopete to backup my own (user) space to a USB disk which seems to work (although I have not tested what happens if it is not there).

However, I'd rather like to 
 a) (If I can't use NAS, see my other issue) backup to another physical disk on my system, but it seems to require me to reformat it. I don't want to do that. I only want to backup my /home/user to that disk, which is small compared to the volume of that disk - which contains other stuff. How can I avoid a reformat requirement.
b) have other users (my wife, kids etc) use cronopete to the same physical disks? It seems to be asking other users than me if they want to reformat the disk ...

**Comment by rastersoft** [comment]
Cronopete needs the backup disks to be in EXT4 or ReiserFS file format because they allow to create hard links. This is a must to allow to keep the size of each backup as low as possible while, at the same time, doing directly accessible backups. It is probable that your external hard disk is formated in NTFS or FAT.

You can always use gparted to reduce the size of the partition in your external hard disk and create a new partition in the needed file format.

About other users, cronopete is designed to allow to use the same disk for all users, keeping the data for each one in different folders.

**Comment by bnlawrence** [comment]
Ah, well, the disk in question is EXT4, and I am having this problem with both the EXT4 internal hard disk and (for other users) the shared USB drive. I might be doing something else wrong. I'll investigate further.

**Comment by rastersoft** [comment]
Another possibility is that your user doesn't have write permissions for the disk's root directory.

**Comment by bnlawrence** [comment]
Ah that's almost certainly it. Thanks. I'll investigate tonight!
